---
services:
 runtime:
  image: nvidia/cuda:13.2.1-runtime-ubuntu24.04
  command: nvidia-smi
  platform: linux/amd64
  network_mode: none
  deploy:
   resources:
    reservations:
     devices:
      - driver: nvidia
        capabilities: [all]
