---
services:
 rabbitmq:
  image: rabbitmq:management
  hostname: rabbitmq
  ports:
   - 5672:5672
   - 15672:15672
  environment:
   - RABBITMQ_DEFAULT_USER=user
   - RABBITMQ_DEFAULT_PASS=password
networks:
 default:
  ipam:
   config:
    - subnet: 10.255.70.88/29
