---
services:
 fedora:
  image: quay.io/fedora/fedora:43
  stdin_open: true  # docker run -i
  tty: true         # docker run -t
networks:
 default:
  ipam:
   config:
    - subnet: 10.255.209.208/29
