# container machine needs systemd
# container image pull quay.io/fedora/fedora:44
FROM quay.io/fedora/fedora:44

COPY certificate.pem /etc/pki/ca-trust/source/anchors/certificate.crt
RUN update-ca-trust extract

RUN \
--mount=type=cache,target=/var/cache/libdnf5 \
--mount=type=cache,target=/var/lib/dnf \
dnf -y install bind-utils hadolint iperf iperf3 jq pylint python3-ansible-lint python3-pip ShellCheck traceroute wget whois yamllint systemd
