---
services:
 centos-stream9:
  image: quay.io/centos/centos:stream9
  stdin_open: true  # docker run -i
  tty: true         # docker run -t
networks:
 default:
  ipam:
   config:
    - subnet: 10.255.150.232/29
