---
services:
 powershell:
  image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
  command: /usr/bin/pwsh ./test.ps1
  volumes:
   - ./scripts:/scripts:ro
  working_dir: /scripts
networks:
 default:
  ipam:
   config:
    - subnet: 10.255.248.136/29
