---
services:
 rust:
  image: rust:latest
  stdin_open: true  # docker run -i
  tty: true         # docker run -t
networks:
 default:
  enable_ipv6: true
  ipam:
   config:
    - subnet: 10.255.255.184/29
