---
services:
 antigravity:
  build:
   dockerfile: Dockerfile
   additional_contexts:
    certs: ../../../certs/
  stdin_open: true  # docker run -i
  tty: true         # docker run -t
  volumes:
    - ./workspace:/workspace
    - ./.antigravity-cli/antigravity-oauth-token:/root/.gemini/antigravity-cli/antigravity-oauth-token
  working_dir: /workspace
networks:
 default:
  enable_ipv6: true
  ipam:
   config:
    - subnet: 10.255.201.8/29
